# Generated by Django 2.2 on 2020-12-03 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('topic', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('video', models.FileField(upload_to='')),
            ],
        ),
    ]
