# Generated by Django 2.2 on 2020-12-03 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='time',
            field=models.TimeField(default=''),
        ),
    ]
