# Generated by Django 2.2 on 2020-12-03 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_content_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='time',
            field=models.TimeField(),
        ),
    ]
