# Generated by Django 2.2 on 2020-12-03 14:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_auto_20201203_0603'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
