# Generated by Django 2.2 on 2020-12-03 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_content_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='date',
        ),
        migrations.RemoveField(
            model_name='content',
            name='time',
        ),
    ]
