# Generated by Django 2.2 on 2020-12-03 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_auto_20201203_0607'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='ddescription',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
