# Generated by Django 2.2 on 2020-12-03 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_content_ddescription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='content',
            old_name='ddescription',
            new_name='dddescription',
        ),
    ]
