# Generated by Django 2.2 on 2020-12-03 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0007_auto_20201203_0614'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='dddescription',
        ),
    ]
