# Generated by Django 2.2 on 2020-12-03 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0010_auto_20201203_1352'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('topic', models.CharField(max_length=200)),
                ('answer', models.TextField(default='')),
            ],
        ),
        migrations.RemoveField(
            model_name='content',
            name='answer',
        ),
    ]
